export function generateRandomCnic() {
  const firstPart = Math.max(Math.floor(Math.random() * 99999), 10000); // Generate a random 4-digit number (1000-9999)
  const secondPart = Math.max(Math.floor(Math.random() * 9999999), 1000000); // Generate a random 7-digit number
  const thirdPart = Math.min(Math.floor(Math.random() * 9), 9); // Generate a random digit (1-10)

  // Combine parts with hyphens
  const cnic = `${firstPart}-${secondPart}-${thirdPart}`;

  return cnic;
}

// ... (rest of the functions)
export function generateRandomBirthdate() {
  const year = Math.floor(Math.random() * (2008 - 1950) + 1950);
  const month = String(Math.floor(Math.random() * 12) + 1).padStart(2, "0");
  const day = String(Math.floor(Math.random() * 28) + 1).padStart(2, "0"); // Simplified
  const birthdate = `${year}-${month}-${day}`;
  return birthdate;
}

export function generateRandomFirstName() {
  const firstNames = [
    "Liam",
    "Noah",
    "Oliver",
    "William",
    "James",
    "Elijah",
    "Benjamin",
    "Lucas",
    "Mason",
    "Ethan",
    "Alexander",
    "Jacob",
    "Michael",
    "Logan",
    "David",
    "Daniel",
    "Henry",
    "Matthew",
    "Samuel",
    "Joseph",
    "Levi",
    "John",
    "Owen",
    "Christian",
    "Isaac",
    "Wyatt",
    "Andrew",
    "Joshua",
    "Connor",
    "Caleb",
    "Ryan",
    "Christopher",
    "Adam",
    "Nathan",
    "Carter",
    "Jayden",
    "Dylan",
    "Gabriel",
    "Lincoln",
    "Thomas",
    "Landon",
    "Hunter",
    "Julian",
    "Ezra",
    "Aaron",
    "Charles",
    "Jordan",
    "Isaiah",
    "Jeremiah",
    "Gavin",
    "Joshua",
    "Angel",
    "Harper",
    "Sophia",
    "Emma",
    "Olivia",
    "Isabella",
    "Ava",
    "Mia",
    "Charlotte",
    "Amelia",
    "Sophia",
    "Olivia",
    "Isabella",
    "Ava",
    "Mia",
    "Amelia",
    "Evelyn",
    "Harper",
    "Emily",
    "Abigail",
    "Elizabeth",
    "Chloe",
    "Madison",
    "Ella",
    "Grace",
    "Avery",
    "Mila",
    "Sofia",
    "Eleanor",
    "Luna",
    "Scarlett",
    "Camila",
    "Aria",
    "Layla",
    "Penelope",
    "Nora",
    "Lily",
    "Zoe",
    "Victoria",
    "Hannah",
    "Ellie",
    "Audrey",
    "Claire",
    "Skylar",
    "Brooke",
    "Genesis",
    "Paisley",
    "Riley",
    "Elena",
  ];
  const randomIndex = Math.floor(Math.random() * firstNames.length);
  return firstNames[randomIndex];
}

export function generateRandomLastName() {
  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Lewis",
    "Robinson",
    "Walker",
    "Wright",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Wood",
    "Perez",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Murphy",
    "Cook",
    "Rogers",
    "Morgan",
    "Peterson",
    "Cooper",
    "Reed",
    "Bailey",
    "Bell",
    "Gomez",
    "Kelly",
    "Cox",
    "Diaz",
    "Gray",
    "Long",
    "Diaz",
    "Cruz",
    "Sanders",
    "Price",
    "Bennett",
    "Murphy",
    "Powell",
    "Brooks",
    "Pierce",
    "Velasquez",
    "Jenkins",
    "Ward",
    "Ford",
    "Mitchell",
    "Fisher",
    "Carter",
    "Roberts",
    "Griffin",
    "Ferguson",
    "Coleman",
    "Young",
    "Sanders",
  ];
  const randomIndex = Math.floor(Math.random() * lastNames.length);
  return lastNames[randomIndex];
}
